### ISSUE TITLE
nested items

### ISSUE THREAD

**Issue by adamski** [toymachiner62/node-mongo-seeds#13]
Does this module currently support nested modules? 
Happy to contribute if not.

**Comment by toymachiner62** [comment]
Can you elaborate on what you mean by nested modules and your use case?

On Wednesday, March 4, 2015, Adam Wilson <notifications@github.com> wrote:

> Does this module currently support nested modules?
> Happy to contribute if not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toymachiner62/node-mongo-seeds/issues/13>.
>


-- 
Tom Caflisch
507.202.0087
TomCaflisch@gmail.com
http://allthingswebdesign.com

**Comment by adamski** [comment]
Yes, we have a tree structure with e.g. ```parent``` field. Also for cases where a document is stored with another. Basically would be good to be able to create references without first giving each item an ```_id```. If this is possible?

**Comment by toymachiner62** [comment]
If you have an [embedded](http://docs.mongodb.org/manual/core/data-model-design/) document than yes you can create those because they are just a part of the json.

For a [normalized](http://docs.mongodb.org/manual/core/data-model-design/) document, that is not currently supported. The problem is that you can't use things like [mongodb's](https://github.com/mongodb/node-mongodb-native) `ObjectID()` function in a JSON file.

If you want to contribute i'm happy to accept pull requests.
