### ISSUE TITLE
Provide an option to upsert data instead of clearing all the data while seeding

### ISSUE THREAD

**Issue by yahyapo** [toymachiner62/node-mongo-seeds#31]
Can a flag be provided, eg. seed --upsert, which does not clear all the existing data in the database but only upserts ( inserts a record if not present or updates it if present ) it?

**Comment by toymachiner62** [comment]
There's some use cases that would have to be outlined if we added something like this. 

I'm assuming you don't want to blow away your db and re-seed b/c you've added some records to your db via your application?

**Comment by yahyapo** [comment]
Yes precisely. Many a times, developers create their own specific records with some specific values which they do not add to the seed. Currently, this data would be blown away when we run the "seed" command. Hence, would like to have a provision whereby the already created data remains and only the newly added / modified data gets updated in the database.

**Comment by toymachiner62** [comment]
These are the use cases off the top of my head that I can think of that need to be figured out how to handle appropriately:

1. What if a file is deleted from the seeds folder? Would you expect that collection to be deleted from mongo?
2. How would you identify records that were inserted from the seeds file since we don't specify OID's in the seed files?
